#!/usr/bin/env bash

grep -q "source ~/.asdf/asdf.sh" ~/.bash_profile || \
  echo "source ~/.asdf/asdf.sh" >> ~/.bash_profile

grep -q "source ~/.asdf/completions/asdf.bash" ~/.bash_profile || \
  echo "source ~/.asdf/completions/asdf.bash" >> ~/.bash_profile
