#!/usr/bin/env bash -e

source utils.sh

fish_path=$(which fish)

if ! grep -q "fish" /etc/shells; then
  sudo_once "sudo required to change default shell"
  echo "$fish_path" | sudo tee -a /etc/shells
fi

default_shell=$(dscl . -read ~/ UserShell | sed 's/UserShell: //')

if [[ "$default_shell" != "$fish_path" ]]; then
  chsh -s "$fish_path"
fi

# Install a fish package manager
curl -sL https://git.io/fisher | source &&
  fisher install jorgebucaran/fisher &&
  fisher update # Installs fish_plugins from dotfiles
