#!/usr/bin/env bash -e

source utils.sh

fish_path=$(which fish)

if ! grep -q "fish" /etc/shells; then
  sudo_once "Password required to change default shell"
  echo "$fish_path" | sudo tee -a /etc/shells
fi

default_shell=$(dscl . -read ~/ UserShell | sed 's/UserShell: //')

if [[ "$default_shell" != "$fish_path" ]]; then
  chsh -s "$fish_path"
fi
