#!/usr/bin/env bash -e

source utils.sh

fish_path=$(which fish)

if ! grep -q "fish" /etc/shells; then
  sudo_once "Password required to change default shell"
  echo "$fish_path" | sudo tee -a /etc/shells
fi

chsh -s "$fish_path"
