#!/usr/bin/env bash -e

source utils.sh

# Install latest asdf version

if [[ ! -d ~/.asdf ]]; then
  remote="https://github.com/asdf-vm/asdf.git"

  latest_tag=$(
    git ls-remote --tags --exit-code --refs "$remote" | \
    sed -E 's/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/g' | \
    tail -n1
  )

  git clone "$remote" --depth 1 --branch "$latest_tag" ~/.asdf
fi

# Setup for bash
grep -q "source ~/.asdf/asdf.sh" ~/.bashrc || \
  echo "source ~/.asdf/asdf.sh" >> ~/.bashrc

grep -q "source ~/.asdf/completions/asdf.bash" ~/.bashrc || \
  echo "source ~/.asdf/completions/asdf.bash" >> ~/.bashrc

source ~/.bashrc

# Setup for zsh
grep -q "source ~/.asdf/asdf.sh" ~/.zshrc || \
  echo "source ~/.asdf/asdf.sh" >> ~/.zshrc

grep -q "source ~/.asdf/completions/asdf.bash" ~/.zshrc || \
  echo "source ~/.asdf/completions/asdf.bash" >> ~/.zshrc

# Setup for fish
if is_available fish; then
  grep -q "source ~/.asdf/asdf.fish" ~/.config/fish/config.fish || \
    echo "source ~/.asdf/asdf.fish" >> ~/.config/fish/config.fish

  mkdir -p ~/.config/fish/completions && ln -s ~/.asdf/completions/asdf.fish ~/.config/fish/completions
fi
