#!/usr/bin/env bash

if ! [[ $(command -v brew) ]]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew analytics off
brew update

taps=(
  'git-duet/tap'
  'homebrew/bundle'
  'homebrew/dupes'
  'homebrew/services'
)

formulas=(
  'autoconf'
  'automake'
  'bash'
  'bat'
  'cloc'
  'cmake'
  'colordiff'
  'coreutils'
  'curl'
  'diff-so-fancy'
  'exa'
  'ffmpeg --with-faac'
  'findutils --with-default-names'
  'fish'
  'gawk'
  'git'
  'git-duet'
  'git-lfs'
  'gitleaks'
  'gnu-getopt'
  'gnu-indent --with-default-names'
  'gnu-sed --with-default-names'
  'gnu-tar --with-default-names'
  'gnu-time --with-default-names'
  'gnu-units --with-default-names'
  'gnu-which --with-default-names'
  'gnutls'
  'go'
  'gobject-introspection'
  'grep'
  'gzip'
  'heroku'
  'highlight'
  'htop-osx'
  'httpie'
  'hub'
  'imagemagick'
  'insect'
  'jp2a'
  'jpeg'
  'jq'
  'less'
  'lzop'
  'make'
  'md5sha1sum'
  'moreutils'
  'ncdu'
  'neovim'
  'node'
  'openssl'
  'pgcli'
  'pngquant'
  'poppler'
  'postgresql'
  'python3'
  'rbenv'
  'rbenv-default-gems'
  'rbenv-gem-rehash'
  'redis'
  'rename'
  'ripgrep'
  'ripgrep-all'
  'rsync'
  'ruby-build'
  'shellcheck'
  'the_silver_searcher'
  'tldr'
  'trash'
  'tree'
  'vim --override-system-vi --with-python3'
  'watch'
  'wget'
  'youtube-dl'
  # 'git-number' # TODO: Enable once aliases are set up.
)

dupes=(
  'grep --with-default-names'
  'less'
  'make --with-default-names'
  # 'openssh' # Disabled because it lacks keychain support.
  'rsync'
  'screen'
  'unzip'
  'gzip'
)

casks=(
  '1password'
  'alfred'
  'atom'
  'bonjour-browser'
  'caffeine'
  'copyq'
  'dash'
  'docker'
  'etcher'
  'firefox'
  'flux'
  'flycut'
  'github-desktop'
  'google-chrome'
  'google-chrome-canary'
  'imageoptim'
  'insomnia'
  'iterm2'
  'java'
  'kap'
  'mactex'
  'ngrok'
  'pgadmin4'
  'psequel'
  'rdm'
  'rowanj-gitx'
  'screenhero'
  'skype'
  'slack'
  'spectacle' # Alternative to shifit
  'visual-studio-code'
  'vlc'
  # 'mongohub'
  # 'little-snitch'
  # 'dropbox' # Has issues with 2FA. Go to https://www.dropbox.com/install.
)

for tap in "${taps[@]}"; do
  brew tap "$tap"
done

for formula in "${formulas[@]}"; do
  eval "brew install ${formula}"
done

for dupe in "${dupes[@]}"; do
  eval "brew install ${dupe}"
done

for cask in "${casks[@]}"; do
  brew cask install "$cask"
done
