#!/usr/bin/env bash

if ! [[ $(command -v brew) ]]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew install caskroom/cask/brew-cask

taps=(
  'git-duet/tap'
  'homebrew/bundle'
  'homebrew/dupes'
)

formulas=(
  'autoconf'
  'automake'
  'bash'
  'cloc'
  'cmake'
  'colordiff'
  'coreutils'
  'ffmpeg'
  'findutils --with-default-names'
  'fish'
  'gawk'
  'git-duet'
  'git-lfs'
  'git'
  'gnu-getopt'
  'gnu-indent --with-default-names'
  'gnu-sed --with-default-names'
  'gnu-tar --with-default-names'
  'gnu-time --with-default-names'
  'gnu-units --with-default-names'
  'gnu-which --with-default-names'
  'gnutls'
  'go'
  'heroku-toolbelt'
  'htop-osx'
  'httpie'
  'hub'
  'imagemagick'
  'jp2a'
  'md5sha1sum'
  'node'
  'openssl'
  'postgresql'
  'python3'
  'rbenv-default-gems'
  'rbenv-gem-rehash'
  'rbenv'
  'redis'
  'ruby-build'
  'the_silver_searcher'
  'trash'
  'tree'
  'vim --override-system-vi --with-python3'
  'watch'
  'wget'
  'youtube-dl'
  # 'git-number' # TODO: Enable once aliases are set up.
)

dupes=(
  'grep --with-default-names'
  'less'
  'make --with-default-names'
  'openssh'
  'rsync'
  'screen'
  'unzip'
  'gzip'
)

casks=(
  '1password'
  'alfred'
  'alfred'
  'bonjour-browser'
  'caffeine'
  'dash'
  'firefox'
  'flux'
  'flycut'
  'github-desktop'
  'google-chrome'
  'hipchat'
  'iterm2'
  'java'
  'little-snitch'
  'pepper-flash'
  'pgadmin3'
  'psequel'
  'rdm'
  'rowanj-gitx'
  'screenhero'
  'slack'
  'spectacle'
  'vlc'
  # 'shiftit'
  # 'mongohub'
  # 'skype'
  # 'dropbox'
  # TODO: docker
)

for tap in "${taps[@]}"; do
  brew tap "$tap"
done

for formula in "${formulas[@]}"; do
  brew install "$formula"
done

for dupe in "${dupes[@]}"; do
  brew install "$dupe"
done

for cask in "${casks[@]}"; do
  brew cask install "$cask" --appdir="/Applications"
done
