#!/usr/bin/env bash -e

source utils.sh

if ! [[ $(command -v brew) ]]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew analytics off
brew update

taps=(
  'homebrew/bundle'
  'homebrew/services'
)

formulas=(
  'airshare'
  'autoconf'
  'automake'
  'bandwhich'
  'bash'
  'bat'
  'cloc'
  'cmake'
  'colordiff'
  'coreutils'
  'ctags'
  'curl'
  'diff-pdf'
  'diff-so-fancy'
  'dos2unix'
  'exa'
  'fd'
  'ffmpeg --with-faac'
  'findomain'
  'findutils'
  'fish'
  'fzf'
  'gawk'
  'git'
  'git-filter-repo'
  'git-lfs'
  'gitleaks'
  'glow'
  'gnu-getopt'
  'gnu-indent'
  'gnu-sed'
  'gnu-tar'
  'gnu-time'
  'gnu-units'
  'gnu-which'
  'gnutls'
  'go'
  'gobject-introspection'
  'grep'
  'grep'
  'gzip'
  'gzip'
  'heroku'
  'highlight'
  'htop-osx'
  'httpie'
  'hub'
  'imagemagick'
  'insect'
  'jp2a'
  'jpeg'
  'jq'
  'less'
  'less'
  'lzop'
  'make'
  'make'
  'md5sha1sum'
  'moreutils'
  'ncdu'
  'neovim'
  'openssl'
  'pgcli'
  'pngquant'
  'poppler'
  'postgresql'
  'python3'
  'readline'
  'redis'
  'rename'
  'ripgrep-all'
  'ripgrep'
  'rsync'
  'rsync'
  'screen'
  'shellcheck'
  'the_silver_searcher'
  'tldr'
  'trash'
  'tree'
  'unzip'
  'vim --override-system-vi --with-python3'
  'watch'
  'wget'
  'youtube-dl'
  # 'git-number' # TODO: Enable once aliases are set up.
  # 'openssh' # Disabled because it lacks keychain support.
)

casks=(
  '1password'
  'alfred'
  'atom'
  'bonjour-browser'
  'caffeine'
  'copyq'
  'dash'
  'devdocs'
  'docker'
  'etcher'
  'firefox'
  'flux'
  'flycut'
  'github-desktop'
  'google-chrome'
  'google-chrome-canary'
  'imageoptim'
  'insomnia'
  'iterm2'
  'java'
  'kap'
  'lepton'
  'mactex'
  'ngrok'
  'pgadmin4'
  'psequel'
  'rdm'
  'rowanj-gitx'
  'screenhero'
  'skype'
  'slack'
  'spectacle' # Alternative to shifit
  'visual-studio-code'
  'vlc'
  'xquartz'
  # 'mongohub'
  # 'little-snitch'
  # 'dropbox' # Has issues with 2FA. Go to https://www.dropbox.com/install.
)

for tap in "${taps[@]}"; do
  brew tap "$tap"
done

for cask in "${casks[@]}"; do
  brew cask install "$cask"
done

for formula in "${formulas[@]}"; do
  eval "brew install ${formula}"
done

# Use GNU commands without "g" prefix.

grep -q "gnubin" ~/.bash_profile || \
  echo 'PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"' >> ~/.bash_profile

if is_available fish; then
  add_to_user_path "/usr/local/opt/coreutils/libexec/gnubin"
fi
