#!/usr/bin/env bash -e

source utils.sh && source ~/.bashrc

asdf plugin add golang
asdf plugin update golang

asdf install golang latest
asdf reshim golang

latest=$(asdf latest golang)
asdf set --home golang "$latest"

log_info "Installed Go $latest."
log_info "Remember to run 'asdf reshim golang' after installing Go CLI packages."
