#!/usr/bin/env bash -e

source utils.sh && source ~/.bashrc

asdf plugin add nodejs
asdf plugin update nodejs

asdf install nodejs latest
asdf reshim nodejs

latest=$(asdf latest nodejs)
asdf set --home nodejs "$latest"

log_info "Installed Node $latest."
log_info "Remember to run 'asdf reshim nodejs' after installing NodeJS CLI packages."
