#!/usr/bin/env bash -e

source utils.sh

asdf plugin-add nodejs && status=$? || status=$?

# `asdf plugin-add` returns exit code 2 when plugin already installed, but it's not an error.
[[ $status -ne 0 && $status -ne 2 ]] && exit $status

asdf plugin update nodejs

asdf install nodejs latest
asdf global nodejs $(asdf latest nodejs)
