#!/usr/bin/env bash -e

source utils.sh && source ~/.bashrc

asdf plugin-add python && status=$? || status=$?

# `asdf plugin-add` returns exit code 2 when plugin already installed, but it's not an error.
[[ $status -ne 0 && $status -ne 2 ]] && exit $status

asdf plugin update python

asdf install python latest:3
asdf global python $(asdf latest python)

pip3 install --upgrade pip setuptools

python3 -m pip install --upgrade --user pipx # Note --user installs to ~/.local/bin
python3 -m pipx ensurepath

if is_available fish; then
  fish -c 'set --universal fish_user_paths $HOME/.local/bin $fish_user_paths'
fi

log_info "Installed Python."
