#!/usr/bin/env bash -e

source utils.sh

asdf plugin-add python
asdf install python latest:2
asdf install python latest:3
asdf global python $(asdf latest python)

pip2 install --upgrade pip setuptools
pip3 install --upgrade pip setuptools
