#!/usr/bin/env bash -e

source utils.sh

if brew --prefix readline > /dev/null
  set --export RUBY_CONFIGURE_OPTS "$RUBY_CONFIGURE_OPTS --with-readline-dir=(brew --prefix readline)"
end

if brew --prefix openssl > /dev/null
  set --export RUBY_CONFIGURE_OPTS "$RUBY_CONFIGURE_OPTS --with-openssl-dir=(brew --prefix openssl)"
end

asdf plugin-add ruby
asdf install ruby latest
asdf global ruby $(asdf latest ruby)
