#!/usr/bin/env bash -e

source utils.sh && source ~/.bashrc

if brew --prefix readline > /dev/null; then
  export RUBY_CONFIGURE_OPTS="$RUBY_CONFIGURE_OPTS --with-readline-dir=$(brew --prefix readline)"
fi

if brew --prefix openssl > /dev/null; then
  export RUBY_CONFIGURE_OPTS="$RUBY_CONFIGURE_OPTS --with-openssl-dir=$(brew --prefix openssl)"
fi

asdf plugin-add ruby && status=$? || status=$?

# `asdf plugin-add` returns exit code 2 when plugin already installed, but it's not an error.
[[ $status -ne 0 && $status -ne 2 ]] && exit $status

asdf plugin update ruby

asdf install ruby latest
asdf global ruby $(asdf latest ruby)

log_info "Installed Ruby."
