#!/usr/bin/env bash -e

source utils.sh && source ~/.bashrc

if brew --prefix readline > /dev/null; then
  export RUBY_CONFIGURE_OPTS="$RUBY_CONFIGURE_OPTS --with-readline-dir=$(brew --prefix readline)"
fi

if brew --prefix openssl > /dev/null; then
  export RUBY_CONFIGURE_OPTS="$RUBY_CONFIGURE_OPTS --with-openssl-dir=$(brew --prefix openssl)"
fi

asdf plugin add ruby
asdf plugin update ruby

asdf install ruby latest
asdf reshim ruby

latest=$(asdf latest ruby)
asdf set --home ruby "$latest"

log_info "Installed Ruby $latest."
log_info "Remember to run 'asdf reshim ruby' after installing Ruby CLI packages."
